### ISSUE TITLE
Target Link

### ISSUE THREAD

**Issue by andymayo** [planetapex/apex-plugin-kpiNumericCard#1]
Hi
 Great plugin thanks. I am struggling to get the target link to work from the card, any ideas if put in the link
 f?p=&APP_ID.:5:&SESSION.::&DEBUG.::::

but nothing happens? Does this feature work?

**Comment by planetapex** [comment]
Thanks for liking the plugin. Sorry for answering after quite a while. The Target Link does not work right now. Hoping to Include this feature some day.
